# Personal Information
author: 
  name: Iago Cupeiro Figueroa
  company: Cupeiro Sinte
  birthday: 27/10/1990
  age: 33
  city: San Martiño de Guillar, Outeiro de Rei, Lugo
  phone: (+34) 628 011 783
  email: iagocupeiro@protonmail.com
  contact-form-id: https://formspree.io/f/<your-id> #Necessary to use form to send emails
  twitter: ""
  facebook: ""
  googleplus: ""
  instagram: ""
  github: https://www.github.com/cupeiro-sinte
  linkedin: https://www.linkedin.com/in/iagocupeiro

year: "2023"

defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "default"
      language: "en"
  - scope:
      path: "es"
      type: "pages"
    values:
      layout: "default"
      languages: es
  - scope:
      path: "en"
      type: "pages"
    values:
      layout: "default"
      languages: en

languages:
  - code: "en"
    name: "English"
    path: "/en"
  - code: "es"
    name: "Español"
    path: "/es"
  - code: "gl"
    name: "Galego"
    path: "/gl"    

exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md