# Personal Information
author: 
  name: Iago Cupeiro Figueroa
  company: Cupeiro Sinte
  birthday: 27/10/1990
  age: 33
  city: San Martiño de Guillar <br> 27154 Outeiro de Rei, Lugo, Galicia
  phone: (+34) 628 011 783
  email: iagocupeiro@protonmail.com
  twitter: ""
  facebook: ""
  googlescholar: https://scholar.google.es/citations?user=oLEFheIAAAAJ&hl=es
  instagram: ""
  researchgate: https://www.researchgate.net/profile/Iago-Cupeiro
  github: https://www.github.com/cupeiro-sinte
  linkedin: https://www.linkedin.com/in/iagocupeiro

year: "2023"

defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "default"
      language: "en"
  - scope:
      path: "gl"
      type: "pages"
    values:
      layout: "default"
      languages: gl
  - scope:
      path: "es"
      type: "pages"
    values:
      layout: "default"
      languages: es
  - scope:
      path: "en"
      type: "pages"
    values:
      layout: "default"
      languages: en

languages:
  - code: "en"
    name: "English"
    path: "/en"
  - code: "es"
    name: "Español"
    path: "/es"
  - code: "gl"
    name: "Galego"
    path: "/gl"    

exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md